services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
    ports:
      - "2181:2181"
  
  kafka-node-1:
    image: confluentinc/cp-kafka:7.6.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka-node-1:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: HOST:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
    depends_on:
      - zookeeper
  
  kafka-node-2:
    image: confluentinc/cp-kafka:7.6.1
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: HOST://0.0.0.0:9094,DOCKER://0.0.0.0:9095
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9094,DOCKER://kafka-node-2:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: HOST:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
    depends_on:
      - zookeeper
  
  init-kafka-script:
    image: confluentinc/cp-kafka:7.6.1
    command: >
      bash -c "
      cub kafka-ready -b kafka-node-1:9093,kafka-node-2:9095 1 60 &&
      kafka-topics --create --if-not-exists --bootstrap-server kafka-node-1:9093,kafka-node-2:9095 --topic currency_rates_changes --partitions 1 --replication-factor 2 --config retention.ms=3600000 &&
      kafka-topics --create --if-not-exists --bootstrap-server kafka-node-1:9093,kafka-node-2:9095 --topic currency_statistics --partitions 1 --replication-factor 2 --config retention.ms=3600000 &&
      kafka-topics --create --if-not-exists --bootstrap-server kafka-node-1:9093,kafka-node-2:9095 --topic currency_purchases --partitions 1 --replication-factor 2 --config retention.ms=3600000
      "
    depends_on:
      - kafka-node-1
      - kafka-node-2
  
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "7777:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-node-1:9093,kafka-node-2:9095
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka-node-1
      - kafka-node-2
      - init-kafka-script